from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Any

from adapters.interfaces import RepoRef
from adapters.registry import AdapterRegistry


TEMPLATES: dict[str, dict[str, str]] = {
    "python-fastapi": {
        "README.md": "# {{service_name}}\n\nGenerated by AIOps Platform.",
        "app/main.py": "from fastapi import FastAPI\n\napp = FastAPI(title='{{service_name}}')\n\n@app.get('/healthz')\ndef healthz():\n    return {'status': 'ok'}\n",
        ".github/workflows/ci.yaml": "name: ci\non: [pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: echo 'run tests'\n",
        "gitops/base/deployment.yaml": "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {{service_name}}\nspec:\n  template:\n    spec:\n      containers:\n      - name: {{service_name}}\n        image: {{image_repo}}:{{image_tag}}\n",
        "gitops/overlays/dev/kustomization.yaml": "resources:\n  - ../../base/deployment.yaml\n",
        "gitops/overlays/stage/kustomization.yaml": "resources:\n  - ../../base/deployment.yaml\n",
        "gitops/overlays/prod/kustomization.yaml": "resources:\n  - ../../base/deployment.yaml\n",
        "catalog-info.yaml": "apiVersion: backstage.io/v1alpha1\nkind: Component\nmetadata:\n  name: {{service_name}}\n  description: {{service_description}}\nspec:\n  type: service\n  lifecycle: production\n  owner: {{owner}}\n",
    },
    "python-worker": {
        "README.md": "# {{service_name}} worker\n",
        "worker/main.py": "def run():\n    print('worker {{service_name}} started')\n",
        "gitops/base/deployment.yaml": "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {{service_name}}-worker\n",
        "catalog-info.yaml": "apiVersion: backstage.io/v1alpha1\nkind: Component\nmetadata:\n  name: {{service_name}}\nspec:\n  type: service\n  lifecycle: production\n  owner: {{owner}}\n",
    },
    "react-frontend": {
        "README.md": "# {{service_name}} frontend\n",
        "src/App.tsx": "export default function App(){return <div>{{service_name}}</div>}\n",
        "package.json": "{\"name\": \"{{service_name}}\", \"private\": true, \"version\": \"0.1.0\"}\n",
        "gitops/base/deployment.yaml": "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {{service_name}}\n",
        "catalog-info.yaml": "apiVersion: backstage.io/v1alpha1\nkind: Component\nmetadata:\n  name: {{service_name}}\nspec:\n  type: website\n  lifecycle: production\n  owner: {{owner}}\n",
    },
}


@dataclass
class ScaffoldResult:
    repo_url: str
    pr_url: str | None
    service_id: str
    argo_apps: list[str]


def _render(text: str, params: Dict[str, Any]) -> str:
    rendered = text
    for key, value in params.items():
        rendered = rendered.replace("{{" + key + "}}", str(value))
    return rendered


class ScaffolderService:
    def __init__(self, registry: AdapterRegistry) -> None:
        self._registry = registry

    def scaffold(self, tenant_id: str, template_id: str, params: Dict[str, Any]) -> ScaffoldResult:
        if template_id not in TEMPLATES:
            raise RuntimeError(f"Unknown template_id: {template_id}")
        required = ["service_name", "owner"]
        missing = [key for key in required if not params.get(key)]
        if missing:
            raise RuntimeError(f"Missing required parameters: {', '.join(missing)}")

        service_name = params["service_name"]
        repo_name = params.get("repo_name", service_name)
        default_branch = params.get("default_branch", "main")
        repo = self._registry.git_provider().scaffold_repo(
            template_ref={"id": template_id},
            parameters={
                "owner": params.get("owner"),
                "repo_name": repo_name,
                "description": params.get("service_description", f"Service {service_name}"),
                "private": params.get("private", True),
                "default_branch": default_branch,
            },
        )

        changes = []
        render_ctx = dict(params)
        render_ctx.setdefault("service_description", f"Service {service_name}")
        render_ctx.setdefault("image_repo", f"ghcr.io/{params.get('owner')}/{repo_name}")
        render_ctx.setdefault("image_tag", "latest")
        for path, content in TEMPLATES[template_id].items():
            changes.append({"path": path, "content": _render(content, render_ctx)})

        pr_ref = self._registry.git_provider().create_pull_request(
            repo_ref=RepoRef(repo_url=repo.repo_url, metadata={"default_branch": default_branch}),
            branch=f"scaffold/{service_name}",
            title=f"Scaffold service {service_name}",
            body=f"Scaffolded from template {template_id}",
            changes=changes,
        )

        return ScaffoldResult(
            repo_url=repo.repo_url,
            pr_url=pr_ref.pr_url,
            service_id=service_name,
            argo_apps=[f"{tenant_id}-{service_name}-dev", f"{tenant_id}-{service_name}-stage", f"{tenant_id}-{service_name}-prod"],
        )
